version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: bid4care-dev
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bid4care
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@my_postgres_db:5432/bid4care?schema=public
      DATABASE_HOST: my_postgres_db
      DATABASE_PORT: 5432
      DATABASE_USER: bid4care-dev
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: bid4care
    depends_on:
      - postgres
    ports:
      - '3000:3000'
volumes:
  postgres_data:
