name: CICD

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bid4care-dev:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/bid4care-dev:${{ github.sha }}

      # - name: Install Dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build

      # - name: Zip The Application
      #   run: zip -r app.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME}}
          environment_name: ${{ secrets.EB_DEV_ENVIRONMENT_NAME}}
          version_label: ${{ github.sha }}
          region: ${{ secrets.AWS_REGION}}
          deployment_package: Dockerrun.aws.json
